// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFVVbJvPCO8HOtMnIB2L7uKDB090VcENs',
    appId: '1:72204959598:web:67f068a34d60c63752cb7f',
    messagingSenderId: '72204959598',
    projectId: 'connectly-66250',
    authDomain: 'connectly-66250.firebaseapp.com',
    storageBucket: 'connectly-66250.firebasestorage.app',
    measurementId: 'G-SP0YQP40R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7cNGFTOZyDtI8mJJhk4LGBLU8euCfGC0',
    appId: '1:72204959598:android:eaa5ccbcdca68c0852cb7f',
    messagingSenderId: '72204959598',
    projectId: 'connectly-66250',
    storageBucket: 'connectly-66250.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc9a4dD5-HXOMyaIXJtfqiVrCIobmEPqU',
    appId: '1:72204959598:ios:54c4f00e06e45ed252cb7f',
    messagingSenderId: '72204959598',
    projectId: 'connectly-66250',
    storageBucket: 'connectly-66250.firebasestorage.app',
    iosBundleId: 'com.example.connectly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc9a4dD5-HXOMyaIXJtfqiVrCIobmEPqU',
    appId: '1:72204959598:ios:54c4f00e06e45ed252cb7f',
    messagingSenderId: '72204959598',
    projectId: 'connectly-66250',
    storageBucket: 'connectly-66250.firebasestorage.app',
    iosBundleId: 'com.example.connectly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFVVbJvPCO8HOtMnIB2L7uKDB090VcENs',
    appId: '1:72204959598:web:bb5cbec0b54693a552cb7f',
    messagingSenderId: '72204959598',
    projectId: 'connectly-66250',
    authDomain: 'connectly-66250.firebaseapp.com',
    storageBucket: 'connectly-66250.firebasestorage.app',
    measurementId: 'G-5Q0665WLM8',
  );
}
